import React from 'react';
import { ArrowUpRight, CheckCircle2 } from 'lucide-react';
import SEOHead from './SEOHead';
import { siteUrl } from '../data/seoPages';
import { trackCtaClick } from '../utils/dataLayer';

const TechnicalPartner: React.FC = () => (
  <article className="relative overflow-hidden bg-[#050505] px-6 pb-28 pt-40 text-white">
    <SEOHead title="Partner tecnico white label per agenzie | Q4 Studio" description="Tracciamento server-side, Consent Mode, automazioni e integrazioni CRM in white label per agenzie." url={`${siteUrl}/partner-tecnico`} noIndex />
    <div className="pointer-events-none absolute left-[-20%] top-10 h-[720px] w-[720px] rounded-full bg-indigo-900/15 blur-[170px]" />
    <div className="relative z-10 mx-auto max-w-5xl">
      <header className="mb-24 max-w-4xl"><p className="mb-5 text-sm uppercase tracking-[0.08em] text-indigo-300">White label · per agenzie</p><h1 className="mb-7 text-[clamp(44px,7vw,88px)] font-bold leading-[0.98] tracking-[-0.045em]">Sono il tecnico che la tua agenzia non ha in casa.</h1><p className="text-xl leading-relaxed text-gray-300 md:text-2xl">Tracciamento server-side, Consent Mode, automazioni, integrazioni CRM. Lavoro white label: il cliente resta tuo, io non lo contatto mai.</p></header>

      <section className="grid gap-10 border-t border-white/10 py-16 md:grid-cols-[0.7fr_1.3fr]"><h2 className="text-3xl font-bold">Il problema che conosci</h2><div className="space-y-5 text-lg leading-relaxed text-gray-300"><p>Il cliente ti scrive che Meta dice 40 conversioni e il suo gestionale ne dice 90. Tu sai che è il tracciamento. Ma sistemare un container server-side, la Consent Mode e le Conversions API non è il lavoro per cui hai assunto il tuo team.</p><p>Così la conversazione si ripete ogni mese, e ogni mese il cliente si fida un po&apos; meno dei numeri che gli porti.</p></div></section>
      <section className="border-t border-white/10 py-16"><h2 className="mb-9 text-3xl font-bold">Come funziona</h2><div className="grid gap-4 md:grid-cols-2">{[['1','Mi giri il problema.','Una call di trenta minuti con te, senza il cliente.'],['2','Ti dico tempi e prezzo.','Fisso, non a ore.'],['3','Lavoro.','Con i tuoi accessi o con quelli del cliente, come preferisci.'],['4','Ti consegno.','Documentazione inclusa, così il tuo team capisce cosa c’è.']].map(([n,t,d]) => <div key={n} className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><span className="text-indigo-300">0{n}</span><h3 className="mb-2 mt-3 text-xl font-bold">{t}</h3><p className="text-gray-400">{d}</p></div>)}</div><p className="mt-7 text-lg text-gray-300">Se serve, sto in call col cliente presentato come tuo tecnico. Se preferisci che non compaia, non compaio.</p></section>
      <section className="rounded-[2rem] border border-indigo-400/25 bg-indigo-400/[0.06] p-8 md:p-12"><p className="mb-5 text-sm uppercase tracking-[0.08em] text-indigo-300">La garanzia che conta</p><h2 className="mb-6 text-3xl font-bold leading-tight">Non contatto i tuoi clienti. Non li aggiungo su LinkedIn. Non li ricontatto quando il progetto finisce.</h2><p className="mb-5 text-gray-300">Se vuoi, lo mettiamo per scritto.</p><p className="leading-relaxed text-gray-300">So che il rischio che ti preoccupa non è il costo: è che il fornitore tecnico diventi il tuo concorrente. Non è il mio modello: io vivo di lavoro tecnico, non di gestione clienti.</p></section>
      <section className="border-t border-white/10 py-16"><h2 className="mb-9 text-3xl font-bold">Cosa faccio</h2><ul className="space-y-5 text-lg text-gray-300">{['Tracciamento server-side: container, Consent Mode v2, Conversions API, Enhanced Conversions. Da 1.500 €, circa una giornata per siti non-ecommerce.', 'Audit tracciamento: 490 €, 3-5 giorni. Utile da rivendere al cliente come primo passo.', 'Automazioni e integrazioni: richieste inbound strutturate, follow-up, collegamenti CRM. Setup + canone.', 'Siti e landing: quando serve il pezzo che manca.'].map(item => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-5 w-5 flex-shrink-0 text-indigo-300" />{item}</li>)}</ul></section>
      <section className="grid gap-12 border-t border-white/10 py-16 md:grid-cols-2"><div><h2 className="mb-5 text-3xl font-bold">Sul prezzo</h2><p className="leading-relaxed text-gray-300">Non sono un freelance a basso costo, e probabilmente non ti serve. Il mio prezzo è pensato perché tu lo ricarichi: se rivendi un setup a 2.500 € e il tuo costo è 1.500 €, hai marginato mille euro su un lavoro che non sapevi fare.</p></div><div><h2 className="mb-5 text-3xl font-bold">Chi sono</h2><div className="space-y-4 leading-relaxed text-gray-300"><p>Sebastiano, Reggio Emilia. Vengo dal marketing (l&apos;ho studiato e l&apos;ho fatto per anni) e sono tecnico. È una combinazione poco comune, ed è il motivo per cui capisco cosa ti serve senza che debba spiegarmelo due volte.</p><p>Lavoro già con un&apos;agenzia in questo modo: ore prepagate più progetti a prezzo fisso.</p></div></div></section>
      <div className="flex flex-col gap-4 border-t border-white/10 pt-12 sm:flex-row"><a href="https://calendar.notion.so/meet/sebastianor/tg3rl4yct" target="_blank" rel="noopener noreferrer" onClick={() => trackCtaClick({ cta_location: 'technical_partner_page', cta_label: 'Prenota trenta minuti', cta_destination: 'https://calendar.notion.so/meet/sebastianor/tg3rl4yct' })} className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-7 py-4 font-semibold text-[#050505]">Prenota trenta minuti <ArrowUpRight className="h-4 w-4" /></a><a href="mailto:sebastiano@q4.studio" onClick={() => trackCtaClick({ cta_location: 'technical_partner_page', cta_label: 'Scrivimi', cta_destination: 'mailto:sebastiano@q4.studio' })} className="inline-flex items-center justify-center gap-2 rounded-full border border-white/20 px-7 py-4 font-semibold">Scrivimi <ArrowUpRight className="h-4 w-4" /></a></div>
    </div>
  </article>
);

export default TechnicalPartner;
